# Site
name: "Entrenar con Ciencia"
title: "Entrenar con Ciencia"
description: "Jekyll Theme for Blogging"
meta_description: "Jekyll theme for blogging."
logo: 'assets/images/logo_ec.png'
favicon: 'assets/images/favicon.ico'
paginate: 12
baseurl: '/alex'
email: 'wowthemesnet@gmail.com'
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  alex:
    name: Alex Labrin
    display_name: Alex
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: alabrin@live.cl
    web: #
    twitter: #
    description: "Profesor de Educación Fisica"
# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge
